create table route_seat
(
    id         integer generated by default as identity
        primary key,
    creator    varchar(255),
    route_id   varchar(255),
    seat_no    varchar(255),
    status     varchar(255)
        constraint route_seat_status_check
            check ((status)::text = ANY
                   ((ARRAY ['AVAILABLE'::character varying, 'HELD'::character varying, 'SOLD'::character varying, 'BLOCKED'::character varying])::text[])),
    hold_by    varchar(255),
    hold_until timestamp(6) with time zone,
    ticket_id  varchar(255),
    created_at timestamp(6),
    created_by varchar(255),
    updated_at timestamp(6),
    updated_by varchar(255)
);