create table fare_config
(
    id           integer generated by default as identity
        primary key,
    base_price   numeric(38, 2) not null,
    currency     varchar(255)   not null,
    vehicle_type varchar(255)   not null,
    created_at   timestamp(6),
    created_by   varchar(255),
    updated_at   timestamp(6),
    updated_by   varchar(255)
);